package com.namma.santhe.ledger.ui

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.mutableStateOf

// ─── Language Enum ───
enum class AppLanguage {
    ENGLISH,
    KANNADA
}

// ─── All App Strings ───
data class AppStrings(
    // General
    val appName: String,
    val builtForBharat: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val search: String,
    val noData: String,

    // Bottom Nav
    val home: String,
    val customers: String,
    val profile: String,

    // Home Screen
    val totalOutstandingDues: String,
    val pendingUdari: String,
    val todaySales: String,
    val collectedToday: String,
    val quickActions: String,
    val dailySummary: String,
    val addUdari: String,
    val customersWithDues: String,
    val viewAll: String,
    val allCleared: String,
    val noPendingDues: String,
    val overdueAlerts: String,

    // Add Udari
    val customerName: String,
    val typeCustomerName: String,
    val newCustomerWillBeCreated: String,
    val customerSelected: String,
    val amount: String,
    val enterAmount: String,
    val quickAdd: String,
    val addUdariButton: String,
    val submitUdari: String,

    // Customers Page
    val totalCustomers: String,
    val searchCustomer: String,
    val noCustomersYet: String,
    val tapToAddUdari: String,
    val noResultsFound: String,
    val tryDifferentName: String,

    // Customer Ledger
    val transactionHistory: String,
    val netBalance: String,
    val amountPending: String,
    val allClearedTick: String,
    val totalUdari: String,
    val totalPaid: String,
    val lastTransaction: String,
    val daysAgo: String,
    val noTransactionsYet: String,
    val addFirstUdari: String,
    val udariCredit: String,
    val paymentReceived: String,
    val deleteTransaction: String,
    val removeEntry: String,
    val addPhoneWhatsapp: String,

    // Daily Summary
    val todayMarketReport: String,
    val todayYouSold: String,
    val duesPending: String,
    val udariGivenToday: String,
    val collectedTodayLabel: String,
    val totalOutstanding: String,
    val transactionsToday: String,
    val overdueCustomers: String,
    val topOutstanding: String,
    val todayPnL: String,
    val netCollection: String,
    val moreCollectedToday: String,
    val moreCreditGiven: String,

    // Profile
    val myProfile: String,
    val nammaSantheVendor: String,
    val businessOverview: String,
    val financialSummary: String,
    val totalUdariGiven: String,
    val totalCollected: String,
    val outstandingDues: String,
    val collectionRate: String,
    val ofTotalCollected: String,
    val todayActivity: String,
    val todayUdari: String,
    val todayCollected: String,
    val totalTransactions: String,
    val appInfo: String,
    val appNameLabel: String,
    val version: String,
    val storage: String,
    val data: String,
    val internet: String,
    val localOffline: String,
    val onDeviceOnly: String,
    val notRequired: String,
    val languageSettings: String,
    val selectLanguage: String,
    val english: String,
    val kannada: String,
    val withDues: String,
    val overdue: String,

    // Payment
    val recordPayment: String,
    val outstanding: String,
    val paymentAmount: String,
    val fullPayment: String,
    val recordPaymentButton: String,

    // WhatsApp
    val whatsappReminder: String,
    val whatsappMessage: String,
)

// ─── English Strings ───
val EnglishStrings = AppStrings(
    appName = "Namma-Santhe Ledger",
    builtForBharat = "Built for Bharat — Empowering every Santhe vendor",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    search = "Search",
    noData = "No data",

    home = "Home",
    customers = "Customers",
    profile = "Profile",

    totalOutstandingDues = "Total Outstanding Dues",
    pendingUdari = "Pending Udari across all customers",
    todaySales = "Today's Sales",
    collectedToday = "Collected Today",
    quickActions = "Quick Actions",
    dailySummary = "Daily Summary",
    addUdari = "Add Udari",
    customersWithDues = "Customers with Dues",
    viewAll = "View All",
    allCleared = "All Cleared!",
    noPendingDues = "No pending dues. Great job!",
    overdueAlerts = "Overdue Alerts",

    customerName = "Customer Name",
    typeCustomerName = "Type customer name...",
    newCustomerWillBeCreated = "New customer will be created",
    customerSelected = "Customer selected",
    amount = "Amount (₹)",
    enterAmount = "Enter amount...",
    quickAdd = "Quick add:",
    addUdariButton = "Add Udari",
    submitUdari = "Add Udari ₹",

    totalCustomers = "total",
    searchCustomer = "Search customer...",
    noCustomersYet = "No Customers Yet",
    tapToAddUdari = "Tap + to add your first udari",
    noResultsFound = "No Results Found",
    tryDifferentName = "Try a different name",

    transactionHistory = "Transaction History",
    netBalance = "Net Balance",
    amountPending = "Amount Pending",
    allClearedTick = "All Cleared ✓",
    totalUdari = "Total Udari",
    totalPaid = "Total Paid",
    lastTransaction = "Last Txn",
    daysAgo = "days ago",
    noTransactionsYet = "No Transactions Yet",
    addFirstUdari = "Add the first Udari entry",
    udariCredit = "Udari (Credit)",
    paymentReceived = "Payment Received",
    deleteTransaction = "Delete Transaction?",
    removeEntry = "Remove entry?",
    addPhoneWhatsapp = "Add phone number to send WhatsApp reminder",

    todayMarketReport = "Today's Market Report",
    todayYouSold = "Today you sold for",
    duesPending = "Dues pending",
    udariGivenToday = "Udari Given Today",
    collectedTodayLabel = "Collected Today",
    totalOutstanding = "Total Outstanding",
    transactionsToday = "Transactions Today",
    overdueCustomers = "Overdue Customers",
    topOutstanding = "Top Outstanding (by amount)",
    todayPnL = "Today's P&L",
    netCollection = "Net Collection vs Udari",
    moreCollectedToday = "More collected than given today 👍",
    moreCreditGiven = "More credit given than collected today",

    myProfile = "My Profile",
    nammaSantheVendor = "🌿 Namma-Santhe Vendor",
    businessOverview = "Business Overview",
    financialSummary = "Financial Summary",
    totalUdariGiven = "Total Udari Given",
    totalCollected = "Total Collected",
    outstandingDues = "Outstanding Dues",
    collectionRate = "Collection Rate",
    ofTotalCollected = "% of total udari collected",
    todayActivity = "Today's Activity",
    todayUdari = "Today's Udari",
    todayCollected = "Today's Collected",
    totalTransactions = "Total Transactions",
    appInfo = "App Info",
    appNameLabel = "App Name",
    version = "Version",
    storage = "Storage",
    data = "Data",
    internet = "Internet",
    localOffline = "Local (Offline)",
    onDeviceOnly = "On-device only",
    notRequired = "Not Required",
    languageSettings = "Language Settings",
    selectLanguage = "Select Language",
    english = "English",
    kannada = "ಕನ್ನಡ",
    withDues = "With Dues",
    overdue = "Overdue",

    recordPayment = "Record Payment",
    outstanding = "Outstanding",
    paymentAmount = "Payment Amount (₹)",
    fullPayment = "Full Payment",
    recordPaymentButton = "Record Payment ₹",

    whatsappReminder = "WhatsApp Reminder",
    whatsappMessage = "Send reminder via WhatsApp",
)

// ─── Kannada Strings ───
val KannadaStrings = AppStrings(
    appName = "ನಮ್ಮ-ಸಂತೆ ಲೆಜರ್",
    builtForBharat = "ಭಾರತಕ್ಕಾಗಿ — ಪ್ರತಿ ಸಂತೆ ವ್ಯಾಪಾರಿಗೆ",
    save = "ಉಳಿಸಿ",
    cancel = "ರದ್ದು",
    delete = "ಅಳಿಸಿ",
    edit = "ಬದಲಾಯಿಸಿ",
    search = "ಹುಡುಕಿ",
    noData = "ಮಾಹಿತಿ ಇಲ್ಲ",

    home = "ಮನೆ",
    customers = "ಗ್ರಾಹಕರು",
    profile = "ಪ್ರೊಫೈಲ್",

    totalOutstandingDues = "ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ",
    pendingUdari = "ಎಲ್ಲ ಗ್ರಾಹಕರ ಉಧಾರಿ ಬಾಕಿ",
    todaySales = "ಇಂದಿನ ಮಾರಾಟ",
    collectedToday = "ಇಂದು ಸಂಗ್ರಹ",
    quickActions = "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    dailySummary = "ದಿನದ ಸಾರಾಂಶ",
    addUdari = "ಉಧಾರಿ ಸೇರಿಸಿ",
    customersWithDues = "ಬಾಕಿ ಇರುವ ಗ್ರಾಹಕರು",
    viewAll = "ಎಲ್ಲ ನೋಡಿ",
    allCleared = "ಎಲ್ಲ ತೀರಿಸಲಾಗಿದೆ!",
    noPendingDues = "ಯಾವುದೇ ಬಾಕಿ ಇಲ್ಲ. ಶಾಭಾಷ್!",
    overdueAlerts = "ತಡವಾದ ಎಚ್ಚರಿಕೆಗಳು",

    customerName = "ಗ್ರಾಹಕರ ಹೆಸರು",
    typeCustomerName = "ಗ್ರಾಹಕರ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ...",
    newCustomerWillBeCreated = "ಹೊಸ ಗ್ರಾಹಕರನ್ನು ರಚಿಸಲಾಗುವುದು",
    customerSelected = "ಗ್ರಾಹಕರು ಆಯ್ಕೆಯಾಗಿದ್ದಾರೆ",
    amount = "ಮೊತ್ತ (₹)",
    enterAmount = "ಮೊತ್ತ ನಮೂದಿಸಿ...",
    quickAdd = "ತ್ವರಿತ ಸೇರ್ಪಡೆ:",
    addUdariButton = "ಉಧಾರಿ ಸೇರಿಸಿ",
    submitUdari = "ಉಧಾರಿ ಸೇರಿಸಿ ₹",

    totalCustomers = "ಒಟ್ಟು",
    searchCustomer = "ಗ್ರಾಹಕರನ್ನು ಹುಡುಕಿ...",
    noCustomersYet = "ಇನ್ನೂ ಗ್ರಾಹಕರಿಲ್ಲ",
    tapToAddUdari = "+ ಒತ್ತಿ ಮೊದಲ ಉಧಾರಿ ಸೇರಿಸಿ",
    noResultsFound = "ಯಾವ ಫಲಿತಾಂಶವೂ ಸಿಗಲಿಲ್ಲ",
    tryDifferentName = "ಬೇರೆ ಹೆಸರು ಪ್ರಯತ್ನಿಸಿ",

    transactionHistory = "ವ್ಯವಹಾರ ಇತಿಹಾಸ",
    netBalance = "ನಿವ್ವಳ ಬಾಕಿ",
    amountPending = "ಬಾಕಿ ಮೊತ್ತ",
    allClearedTick = "ಎಲ್ಲ ತೀರಿಸಲಾಗಿದೆ ✓",
    totalUdari = "ಒಟ್ಟು ಉಧಾರಿ",
    totalPaid = "ಒಟ್ಟು ಪಾವತಿ",
    lastTransaction = "ಕೊನೆ ವ್ಯವಹಾರ",
    daysAgo = "ದಿನಗಳ ಹಿಂದೆ",
    noTransactionsYet = "ಇನ್ನೂ ವ್ಯವಹಾರಗಳಿಲ್ಲ",
    addFirstUdari = "ಮೊದಲ ಉಧಾರಿ ನಮೂದಿಸಿ",
    udariCredit = "ಉಧಾರಿ (ಸಾಲ)",
    paymentReceived = "ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    deleteTransaction = "ವ್ಯವಹಾರ ಅಳಿಸಬೇಕೇ?",
    removeEntry = "ನಮೂದು ತೆಗೆದುಹಾಕಬೇಕೇ?",
    addPhoneWhatsapp = "WhatsApp ಜ್ಞಾಪನೆಗೆ ಫೋನ್ ಸಂಖ್ಯೆ ಸೇರಿಸಿ",

    todayMarketReport = "ಇಂದಿನ ಸಂತೆ ವರದಿ",
    todayYouSold = "ಇಂದು ನೀವು ಮಾರಿದ್ದು",
    duesPending = "ಬಾಕಿ ಉಳಿದಿದೆ",
    udariGivenToday = "ಇಂದು ಕೊಟ್ಟ ಉಧಾರಿ",
    collectedTodayLabel = "ಇಂದು ಸಂಗ್ರಹ",
    totalOutstanding = "ಒಟ್ಟು ಬಾಕಿ",
    transactionsToday = "ಇಂದಿನ ವ್ಯವಹಾರಗಳು",
    overdueCustomers = "ತಡವಾದ ಗ್ರಾಹಕರು",
    topOutstanding = "ಹೆಚ್ಚು ಬಾಕಿ ಇರುವವರು",
    todayPnL = "ಇಂದಿನ ಲಾಭ-ನಷ್ಟ",
    netCollection = "ಉಧಾರಿ vs ಸಂಗ್ರಹ",
    moreCollectedToday = "ಇಂದು ಹೆಚ್ಚು ಸಂಗ್ರಹಿಸಲಾಗಿದೆ 👍",
    moreCreditGiven = "ಇಂದು ಹೆಚ್ಚು ಉಧಾರಿ ಕೊಡಲಾಗಿದೆ",

    myProfile = "ನನ್ನ ಪ್ರೊಫೈಲ್",
    nammaSantheVendor = "🌿 ನಮ್ಮ-ಸಂತೆ ವ್ಯಾಪಾರಿ",
    businessOverview = "ವ್ಯಾಪಾರ ಸಾರಾಂಶ",
    financialSummary = "ಆರ್ಥಿಕ ಸಾರಾಂಶ",
    totalUdariGiven = "ಒಟ್ಟು ಉಧಾರಿ ಕೊಟ್ಟಿದ್ದು",
    totalCollected = "ಒಟ್ಟು ಸಂಗ್ರಹ",
    outstandingDues = "ಬಾಕಿ ಮೊತ್ತ",
    collectionRate = "ಸಂಗ್ರಹ ಪ್ರಮಾಣ",
    ofTotalCollected = "% ಉಧಾರಿ ಸಂಗ್ರಹವಾಗಿದೆ",
    todayActivity = "ಇಂದಿನ ಚಟುವಟಿಕೆ",
    todayUdari = "ಇಂದಿನ ಉಧಾರಿ",
    todayCollected = "ಇಂದು ಸಂಗ್ರಹ",
    totalTransactions = "ಒಟ್ಟು ವ್ಯವಹಾರಗಳು",
    appInfo = "ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ",
    appNameLabel = "ಅಪ್ ಹೆಸರು",
    version = "ಆವೃತ್ತಿ",
    storage = "ಸಂಗ್ರಹಣೆ",
    data = "ಡೇಟಾ",
    internet = "ಇಂಟರ್ನೆಟ್",
    localOffline = "ಸ್ಥಳೀಯ (ಆಫ್‌ಲೈನ್)",
    onDeviceOnly = "ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ",
    notRequired = "ಅಗತ್ಯವಿಲ್ಲ",
    languageSettings = "ಭಾಷಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    selectLanguage = "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    english = "English",
    kannada = "ಕನ್ನಡ",
    withDues = "ಬಾಕಿ ಇದೆ",
    overdue = "ತಡವಾಗಿದೆ",

    recordPayment = "ಪಾವತಿ ದಾಖಲಿಸಿ",
    outstanding = "ಬಾಕಿ",
    paymentAmount = "ಪಾವತಿ ಮೊತ್ತ (₹)",
    fullPayment = "ಪೂರ್ಣ ಪಾವತಿ",
    recordPaymentButton = "ಪಾವತಿ ದಾಖಲಿಸಿ ₹",

    whatsappReminder = "WhatsApp ಜ್ಞಾಪನೆ",
    whatsappMessage = "WhatsApp ಮೂಲಕ ಜ್ಞಾಪನೆ ಕಳುಹಿಸಿ",
)

// ─── Composition Local for Language ───
val LocalAppStrings = compositionLocalOf { EnglishStrings }
val LocalAppLanguage = compositionLocalOf { mutableStateOf(AppLanguage.ENGLISH) }